### ISSUE TITLE
Right clicking on the work area no longer works

### ISSUE THREAD

**Issue by PawanYr** [StevenReiss/bubbles#5]
After pulling the most recent changes and rebuilding, right clicking on the work area no longer brings up a menu. The following appears in the runlog every time I right click: 

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "edu.brown.cs.bubbles.buda.BudaBubble.addComponentListener(java.awt.event.ComponentListener)" because "bb" is null
        at edu.brown.cs.bubbles.buda.BudaRoot.createSearchBubble(BudaRoot.java:858)
        at edu.brown.cs.bubbles.buda.BudaRoot.createSearchBubble(BudaRoot.java:842)
        at edu.brown.cs.bubbles.buda.BudaBubbleArea.handleMouseEvent(BudaBubbleArea.java:2540)
        at edu.brown.cs.bubbles.buda.BudaBubbleArea.access$500(BudaBubbleArea.java:103)
        at edu.brown.cs.bubbles.buda.BudaBubbleArea$Mouser.mouseClicked(BudaBubbleArea.java:2627)
        at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:277)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6619)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
        at edu.brown.cs.bubbles.buda.BudaBubbleArea.processMouseEvent(BudaBubbleArea.java:2456)
        at edu.brown.cs.bubbles.buda.BudaRoot$MouseEventQueue.dispatchEvent(BudaRoot.java:3086)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by StevenReiss** [comment]
You probably have a problem with the build.  Ensure you update ivy as well and compile it first.  Ensure that all of bubbles compiles correctly.

**Comment by PawanYr** [comment]
The issue seems to have been fixed by updating my eclipse (4.23 -> 4.28); didn't make any other changes or even rebuild before doing that and it was fixed, so I'm not sure what else it could have been. In any case, closing this issue; thanks for your time.
